FROM node:24-alpine3.21

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* ./
RUN npm install

# Copy the source code
COPY . .

EXPOSE 3000

# Start in development mode (with hot reload)
CMD ["npm", "run", "dev"]