services:
  template-service:
    build: ../backend/springboot-services/template-service
    volumes:
      - ../backend/springboot-services/template-service:/app
      - ~/.m2:/root/.m2
    ports:
      - "8001:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - order-db

  order-db:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${ORDER_POSTGRES_DB}
      POSTGRES_USER: ${ORDER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ORDER_POSTGRES_PASSWORD}
