FROM mcr.microsoft.com/dotnet/sdk:9.0
WORKDIR /app

COPY CashierSolution.sln ./
COPY Cashier.API/*.csproj Cashier.API/
COPY Cashier.Core/*.csproj Cashier.Core/
COPY Cashier.Infrastructure/*.csproj Cashier.Infrastructure/
COPY Cashier.Services/*.csproj Cashier.Services/
COPY Cashier.Validation/*.csproj Cashier.Validation/
COPY Cashier.Shared/*.csproj Cashier.Shared/

RUN dotnet restore

COPY . ./
COPY Cashier.Infrastructure/Data/DataSeeding /app/Cashier.Infrastructure/Data/DataSeeding
RUN echo "---- DataSeeding contents ----" && ls -lR /app/Cashier.Infrastructure/Data/DataSeeding || echo "DataSeeding not found"
RUN echo "---- Directory tree for Cashier.Infrastructure/Data ----" && ls -lR /app/Cashier.Infrastructure/Data

EXPOSE 8080

CMD ["dotnet", "watch", "--project", "Cashier.API/Cashier.API.csproj", "run"]