FROM mcr.microsoft.com/dotnet/sdk:9.0
WORKDIR /app

COPY CashierSolution.sln ./
COPY Cashier.API/*.csproj Cashier.API/
COPY Cashier.Core/*.csproj Cashier.Core/
COPY Cashier.Services/*.csproj Cashier.Services/
COPY Cashier.Shared/*.csproj Cashier.Shared/

RUN dotnet restore

EXPOSE 8080

CMD ["dotnet", "watch", "--project", "Cashier.API/Cashier.API.csproj", "run"]