// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reporting.Infrastructure.Data;

#nullable disable

namespace Reporting.Infrastructure.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    partial class OrderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reporting.Core.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 3, 20, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            Total = 250,
                            UpdatedAt = new DateTime(2025, 7, 21, 9, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 7, 21, 12, 45, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            Total = 180
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 5, 22, 8, 20, 0, 0, DateTimeKind.Unspecified),
                            Status = "Cancelled",
                            Total = 0,
                            UpdatedAt = new DateTime(2025, 7, 22, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 7, 22, 15, 10, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            Total = 320,
                            UpdatedAt = new DateTime(2024, 7, 22, 16, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 7, 23, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Processing",
                            Total = 210
                        });
                });

            modelBuilder.Entity("Reporting.Core.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a6a7df2-12a1-4c38-b43e-7b97b1a2c9e5"),
                            CreatedAt = new DateTime(2024, 11, 10, 9, 45, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Logo = "cafebliss-logo.png",
                            Name = "Cafe Bliss"
                        },
                        new
                        {
                            Id = new Guid("1fbb3e8e-a31b-47ec-89c0-83f617d2ab31"),
                            CreatedAt = new DateTime(2023, 4, 22, 13, 20, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Logo = "greengrocers-logo.svg",
                            Name = "Green Grocers"
                        },
                        new
                        {
                            Id = new Guid("7fdc6bd0-7a39-4d5b-8b9f-7332d3eacc2f"),
                            CreatedAt = new DateTime(2025, 1, 15, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Logo = "techbazaar.png",
                            Name = "Tech Bazaar"
                        },
                        new
                        {
                            Id = new Guid("ea1b788c-bb89-4201-82fc-1262b17b0ae6"),
                            CreatedAt = new DateTime(2022, 8, 1, 17, 10, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Logo = "booknest.jpg",
                            Name = "Book Nest"
                        },
                        new
                        {
                            Id = new Guid("c90db1e7-2ec6-447f-a149-9db97ce5e389"),
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Logo = "urbanstyle-logo.webp",
                            Name = "Urban Style"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
